version: '3.8'

services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "127.0.0.1:5432:5432"  # Only accessible from VPS
    env_file:
      - .env.docker
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
            python manage.py create_admin &&
            python manage.py collectstatic --noinput &&
            gunicorn nasom_job_portal.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    ports:
      - "8000:8000"  # ✅ this line exposes it to your browser
    depends_on:
      - db
    env_file:
      - .env.docker
    environment:
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}

    restart: always

volumes:
  postgres_data:
