# Generated by Django 5.1.5 on 2025-07-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification_request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='applicant_message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='ngo_message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='request_date',
            field=models.DateField(null=True),
        ),
    ]
