# Generated by Django 5.1.5 on 2025-07-20 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification_request', '0002_verificationrequest_applicant_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verificationrequest',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='verificationrequest',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='verificationrequest',
            name='phone_number',
        ),
    ]
