# Generated by Django 5.1.5 on 2025-06-22 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_vocation_training', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationvocationaltraining',
            name='completion_status',
        ),
    ]
