# Generated by Django 5.1.5 on 2025-07-12 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_vocation_training', '0002_remove_educationvocationaltraining_completion_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationvocationaltraining',
            name='start_month',
        ),
        migrations.RemoveField(
            model_name='educationvocationaltraining',
            name='start_year',
        ),
    ]
