# Generated by Django 5.1.5 on 2025-06-20 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationuser',
            name='applicant_autism_severity',
        ),
        migrations.RemoveField(
            model_name='applicationuser',
            name='postal_code',
        ),
    ]
