# Generated by Django 5.1.5 on 2025-06-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_user', '0002_remove_applicationuser_applicant_autism_severity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationuser',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
    ]
