# Generated by Django 5.1.5 on 2025-06-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_user', '0003_applicationuser_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationuser',
            name='company_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
