# Generated by Django 5.1.5 on 2025-07-20 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_user', '0004_applicationuser_company_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationuser',
            name='company_email',
        ),
        migrations.RemoveField(
            model_name='applicationuser',
            name='company_phone_number',
        ),
    ]
