# Generated by Django 5.1.5 on 2025-07-23 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_user', '0005_remove_applicationuser_company_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationuser',
            name='looking_job_status',
        ),
    ]
