# Generated by Django 5.1.5 on 2025-07-17 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0001_initial'),
        ('job_ad', '0006_rename_shift_flexicle_desc_jobad_shift_flexible_desc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_status', models.CharField(choices=[('saved', 'Saved'), ('called', 'Called by Employer'), ('pending', 'Pending'), ('shortlisted', 'Shortlisted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('date_applied', models.DateTimeField(blank=True, null=True)),
                ('answer_one', models.TextField(blank=True, null=True)),
                ('answer_two', models.TextField(blank=True, null=True)),
                ('answer_three', models.TextField(blank=True, null=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_applications', to='document.document')),
                ('job_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_applications', to='job_ad.jobad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='make_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'job_ad')},
            },
        ),
    ]
