# Generated by Django 5.1.5 on 2025-06-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_ad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobad',
            name='publish_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired')], default='draft', max_length=10),
        ),
    ]
