# Generated by Django 5.1.5 on 2025-07-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_ad', '0002_alter_jobad_publish_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobad',
            name='job_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
