# Generated by Django 5.1.5 on 2025-07-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_ad', '0003_alter_jobad_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobad',
            name='job_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobad',
            name='less_stressful_env_status',
            field=models.BooleanField(default=False),
        ),
    ]
