# Generated by Django 5.1.5 on 2025-07-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_ad', '0004_jobad_job_location_jobad_less_stressful_env_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobad',
            name='job_category',
            field=models.CharField(blank=True, choices=[('Professional Job', 'Professional Job'), ('Semi-Skilled Job', 'Semi-Skilled Job'), ('Simple Job', 'Simple Job')], max_length=20, null=True),
        ),
    ]
