# Generated by Django 5.1.5 on 2025-07-17 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_ad', '0005_alter_jobad_job_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobad',
            old_name='shift_flexicle_desc',
            new_name='shift_flexible_desc',
        ),
    ]
